/* eslint-disable @typescript-eslint/no-explicit-any */

export const Assets: { [key: string]: any } = {
  trivia_general: require('@/assets/trivia_general.png'),
  error: require('@/assets/error.png'),
  generic_user: require('@/assets/generic_user.png'),
  generic_user_01: require('@/assets/generic_user_01.png'),
  primary_icon: require('@/assets/primary_icon.webp'),
  main_icon: require('@/assets/main_icon.png'),
  secondary_icon: require('@/assets/secondary_icon.png'),
  agenda: require('@/assets/posts/categories/agenda.png'),
  viraluisate: require('@/assets/posts/categories/viraluisate.png'),
  entrevistas: require('@/assets/posts/categories/entrevistas.png'),
  recorridos: require('@/assets/posts/categories/recorridos.png'),
  mensajes_y_spots: require('@/assets/posts/categories/mensajes_y_spots.png'),
  angry_emoji: require('@/assets/angry_emoji.png'),
  annoyed_emoji: require('@/assets/annoyed_emoji.png'),
  depressed_emoji: require('@/assets/depressed_emoji.png'),
  happy_emoji: require('@/assets/happy_emoji.png'),
  in_love_emoji: require('@/assets/in_love_emoji.png'),
  ofended_emoji: require('@/assets/ofended_emoji.png'),
  sad_emoji: require('@/assets/sad_emoji.png'),
  scared_emoji: require('@/assets/scared_emoji.png'),
  smily_emoji: require('@/assets/smily_emoji.png'),
  stuned_emoji: require('@/assets/stuned_emoji.png'),
  suprised_emoji: require('@/assets/suprised_emoji.png'),
  live_icon: require('@/assets/live_icon.jpeg'),
  countries: require('@/assets/addresses/countries.json'),
  chat_icon: require('@/assets/chat_icon.png'),
  splash_screen: require('@/assets/splash_screen.png'),
};

export const CustomFonts = {
  MontserratMedium: 'Montserrat-Medium',
  MontserratBold: 'Montserrat-Bold',
  MontserratLight: 'Montserrat-Light',
  MontserratRegular: 'Montserrat-Regular',
  MontserratExtraLight: 'Montserrat-ExtraLight',
  SanchezRegular: 'Sanchez-Regular',
  BarlowSemiCondensedMedium: 'BarlowSemiCondensed-Medium',
  BarlowSemiCondensedExtraBoldItalic: 'BarlowSemiCondensed-ExtraBoldItalic',
  BarlowSemiCondensedBold: 'BarlowSemiCondensed-Bold',
  BarlowSemiCondensedRegular: 'BarlowSemiCondensed-Regular',
  BarlowBlack: 'Barlow-Black',
  BarlowBold: 'Barlow-Bold',
  BarlowExtraBoldItalic: 'Barlow-ExtraBoldItalic',
  BarlowSemiCondensedSemiBold: 'BarlowSemiCondensed-SemiBold',
  HelveticaNeueLTStdCn: 'HelveticaNeueLTStd-Cn',
};
